import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#f0f4ff",
          100: "#dbe4ff",
          200: "#bac8ff",
          300: "#91a7ff",
          400: "#748ffc",
          500: "#5c7cfa",
          600: "#4c6ef5",
          700: "#4263eb",
          800: "#3b5bdb",
          900: "#364fc7",
          950: "#1e3a8a",
        },
        dark: {
          900: "#0a0a0f",
          800: "#111118",
          700: "#1a1a27",
          600: "#242436",
          500: "#2e2e46",
        },
        warning: "#d97706",
        // v2 — violet/amber/rose premium palette
        primary: "#7C3AED",
        "primary-dark": "#6D28D9",
        "primary-container": "#8B5CF6",
        "on-primary": "#ffffff",
        "on-primary-container": "#F5F3FF",
        "primary-fixed": "#EDE9FE",
        "primary-fixed-dim": "#C4B5FD",
        "inverse-primary": "#C4B5FD",
        "surface-tint": "#7C3AED",
        secondary: "#D97706",
        "secondary-container": "#FDE68A",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#92400E",
        "secondary-fixed": "#FEF3C7",
        "secondary-fixed-dim": "#FCD34D",
        "on-secondary-fixed": "#78350F",
        "on-secondary-fixed-variant": "#92400E",
        tertiary: "#DB2777",
        "tertiary-container": "#FCE7F3",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#831843",
        "tertiary-fixed": "#FCE7F3",
        "tertiary-fixed-dim": "#F9A8D4",
        "on-tertiary-fixed": "#500724",
        "on-tertiary-fixed-variant": "#831843",
        background: "#FDFCFF",
        surface: "#FDFCFF",
        "surface-bright": "#FDFCFF",
        "surface-dim": "#E8E6F0",
        "surface-variant": "#E9E7F4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#F5F3FF",
        "surface-container": "#EEEDF8",
        "surface-container-high": "#E4E2F2",
        "surface-container-highest": "#D9D7EC",
        "on-surface": "#1E1B2E",
        "on-surface-variant": "#47445A",
        "on-background": "#1E1B2E",
        "inverse-surface": "#2D2A3E",
        "inverse-on-surface": "#F0EEF9",
        outline: "#79768C",
        "outline-variant": "#C5C3D6",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "system-ui", "sans-serif"],
        headline: ["var(--font-jakarta)", "var(--font-manrope)", "system-ui", "sans-serif"],
        body: ["var(--font-manrope)", "system-ui", "sans-serif"],
        label: ["var(--font-manrope)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "mesh-gradient":
          "radial-gradient(at 40% 20%, hsla(228,100%,74%,0.3) 0px, transparent 50%), radial-gradient(at 80% 0%, hsla(189,100%,56%,0.2) 0px, transparent 50%), radial-gradient(at 0% 50%, hsla(355,100%,93%,0.2) 0px, transparent 50%)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
