import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#f0f4ff",
          100: "#dbe4ff",
          200: "#bac8ff",
          300: "#91a7ff",
          400: "#748ffc",
          500: "#5c7cfa",
          600: "#4c6ef5",
          700: "#4263eb",
          800: "#3b5bdb",
          900: "#364fc7",
          950: "#1e3a8a",
        },
        dark: {
          900: "#0a0a0f",
          800: "#111118",
          700: "#1a1a27",
          600: "#242436",
          500: "#2e2e46",
        },
        warning: "#d97706",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-variant": "#e0e3e5",
        primary: "#0050cb",
        outline: "#727687",
        "on-surface-variant": "#424656",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c0c1ff",
        background: "#f7f9fb",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001849",
        surface: "#f7f9fb",
        "on-primary-container": "#f8f7ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#002113",
        "surface-container-high": "#e6e8ea",
        "on-secondary-container": "#00714d",
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        "primary-fixed": "#dae1ff",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-tint": "#0054d6",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#003fa4",
        tertiary: "#4345d1",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#07006c",
        secondary: "#006c49",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-fixed-variant": "#005236",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "tertiary-container": "#5d60eb",
        "primary-fixed-dim": "#b3c5ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#faf6ff",
        "surface-bright": "#f7f9fb",
        "secondary-container": "#6cf8bb",
        "tertiary-fixed": "#e1e0ff",
        "outline-variant": "#c2c6d8",
        "inverse-primary": "#b3c5ff",
        "primary-container": "#0066ff",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed-dim": "#4edea3",
      },
      fontFamily: {
        sans: ["var(--font-manrope)", "system-ui", "sans-serif"],
        headline: ["var(--font-manrope)", "system-ui", "sans-serif"],
        body: ["var(--font-manrope)", "system-ui", "sans-serif"],
        label: ["var(--font-manrope)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "mesh-gradient":
          "radial-gradient(at 40% 20%, hsla(228,100%,74%,0.3) 0px, transparent 50%), radial-gradient(at 80% 0%, hsla(189,100%,56%,0.2) 0px, transparent 50%), radial-gradient(at 0% 50%, hsla(355,100%,93%,0.2) 0px, transparent 50%)",
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
